import Curve from '@/components/Layout/Curve'
import PageTransition from '@/components/Layout/PageTransition'
import Container from '@/components/Pages/Container'
import Pricing from '@/components/Pages/Pricing/Pricing'
import Section from '@/components/Pages/Section'
import Head from 'next/head'

export default function Contact() {
  return (
    <>
      <Head>
        <title>Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTransition>
        <Container>
          <Section
              id="pricing"
              title="Pricing"
              description="Simple, transparent pricing. No surprises."
            >
            <Pricing />
          </Section>
        </Container>
      </PageTransition>
    </>
  )
}
