import Hero from "@/components/Pages/Hero";
import Testimonials from "@/components/Pages/Testimonials";
import Pricing from "@/components/Pages/Pricing/Pricing";
import FAQ from "@/components/Pages/FAQ";
import Logos from "@/components/Pages/Logos";
import Benefits from "@/components/Pages/Benefits/Benefits";
import Container from "@/components/Pages/Container";
import Section from "@/components/Pages/Section";
import Stats from "@/components/Pages/Stats";
import CTA from "@/components/Pages/CTA";
import Head from "next/head";
import Curve from "@/components/Layout/Curve";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Curve>
        <Hero />
        <Logos />
        <Container>
          <Benefits />

          <Section
            id="pricing"
            title="Pricing"
            description="Simple, transparent pricing. No surprises."
          >
            <Pricing />
          </Section>

          <Section
            id="testimonials"
            title="What Our Clients Say"
            description="Hear from those who have partnered with us."
          >
            <Testimonials />
          </Section>

          <FAQ />

          <Stats />
          
          <CTA />
        </Container>
      </Curve>
    </>
  );
};

export default HomePage;
