import Curve from '@/components/Layout/Curve'
import PageTransition from '@/components/Layout/PageTransition'
import Container from '@/components/Pages/Container'
import Section from '@/components/Pages/Section'
import Testimonials from '@/components/Pages/Testimonials'
import Head from 'next/head'

export default function Contact() {
  return (
    <>
      <Head>
        <title>Testimonials</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTransition>
        <Container>
          <Section
            id="testimonials"
            title="What Our Clients Say"
            description="Hear from those who have partnered with us."
          >
            <Testimonials />
          </Section>
        </Container>
      </PageTransition>
    </>
  )
}
