import Head from 'next/head'
import Curve from '@/components/Layout/Curve'
import Hero from "@/components/Pages/Hero";
import Logos from "@/components/Pages/Logos";
import Benefits from "@/components/Pages/Benefits/Benefits";
import Container from "@/components/Pages/Container";
import Section from "@/components/Pages/Section";
import Stats from "@/components/Pages/Stats";
import CTA from "@/components/Pages/CTA";
import PageTransition from '@/components/Layout/PageTransition';

export default function Home() {
  return (
    <>
     <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTransition>
        <Hero />
        <Logos />
        <Container>
          <Section>
            <Benefits />
            <Stats />
            <CTA />
          </Section>
        </Container>
      </PageTransition>
    </>
  )
}
