import Curve from '@/components/Layout/Curve'
import PageTransition from '@/components/Layout/PageTransition'
import Container from '@/components/Pages/Container'
import FAQ from '@/components/Pages/FAQ'
import Section from '@/components/Pages/Section'
import Head from 'next/head'

export default function Contact() {
  return (
    <>
      <Head>
        <title>FAQ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTransition>
        <Container>
          <Section>
            <FAQ />
          </Section>
        </Container>
      </PageTransition>
    </>
  )
}
